[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
dependsOn = ['setup']
cmds = ['cd backend && npm ci --only=production']

[phases.build]
dependsOn = ['install']
cmds = ['cd backend && npm run build']

[start]
cmd = 'cd backend && npm start' 