[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
dependsOn = ['setup']
cmds = ['cd backend && npm install --omit=dev --prefer-offline --no-audit --no-fund --silent']

[phases.build]
dependsOn = ['install']
cmds = ['cd backend && npm run build']

[start]
cmd = 'cd backend && npm start' 